### ISSUE TITLE
Daily quests

### ISSUE THREAD

**Issue by Thomasvdp25060** [VortexCraft1/Vortex-Craft#15]
**Describe what you'd like**
Everyone will recieve 5 missions/quests per day. ex: kill 5 players in pvp, kill 25 zombies, harvest 64 carrots,.. If you can complete them all you recieve a reward. These rewards would go from 15k to a vote key (if we are going to have those). 

**Server**
Skyblock, factions, prison

**Reasoning behind this**
This would motivate players to log on every day to complete these quests. 

**Additional context**
![naamloos](https://user-images.githubusercontent.com/42411096/50301967-fab8f700-0488-11e9-9dcb-bf438ff1ad22.png)

**Comment by VortexCraft1** [comment]
We will probably have some sort of quests to complete as you start to play on the server, I like the idea and they could get progressively harder the more you complete. We do have the default skyblock ones (/c) so that will be helpful. 

This idea is definitely being added in some way shape or form.
